@include('frontend.giaodien3.includes.head')
@include('frontend.giaodien3.includes.header')
@yield('content')
@include('frontend.giaodien3.includes.footer_area')
@include('frontend.giaodien3.includes.footer')